module.base_model.features.0.0.weight
module.base_model.features.0.1.weight
module.base_model.features.0.1.bias
module.base_model.features.0.1.running_mean
module.base_model.features.0.1.running_var
module.base_model.features.0.1.num_batches_tracked
module.base_model.features.1.conv.0.weight
module.base_model.features.1.conv.1.weight
module.base_model.features.1.conv.1.bias
module.base_model.features.1.conv.1.running_mean
module.base_model.features.1.conv.1.running_var
module.base_model.features.1.conv.1.num_batches_tracked
module.base_model.features.1.conv.3.weight
module.base_model.features.1.conv.4.weight
module.base_model.features.1.conv.4.bias
module.base_model.features.1.conv.4.running_mean
module.base_model.features.1.conv.4.running_var
module.base_model.features.1.conv.4.num_batches_tracked
module.base_model.features.1.conv.5.conv.weight
module.base_model.features.2.conv.0.weight
module.base_model.features.2.conv.1.weight
module.base_model.features.2.conv.1.bias
module.base_model.features.2.conv.1.running_mean
module.base_model.features.2.conv.1.running_var
module.base_model.features.2.conv.1.num_batches_tracked
module.base_model.features.2.conv.3.weight
module.base_model.features.2.conv.4.weight
module.base_model.features.2.conv.4.bias
module.base_model.features.2.conv.4.running_mean
module.base_model.features.2.conv.4.running_var
module.base_model.features.2.conv.4.num_batches_tracked
module.base_model.features.2.conv.6.weight
module.base_model.features.2.conv.7.weight
module.base_model.features.2.conv.7.bias
module.base_model.features.2.conv.7.running_mean
module.base_model.features.2.conv.7.running_var
module.base_model.features.2.conv.7.num_batches_tracked
module.base_model.features.2.conv.8.conv.weight
module.base_model.features.3.conv.0.weight
module.base_model.features.3.conv.1.weight
module.base_model.features.3.conv.1.bias
module.base_model.features.3.conv.1.running_mean
module.base_model.features.3.conv.1.running_var
module.base_model.features.3.conv.1.num_batches_tracked
module.base_model.features.3.conv.3.weight
module.base_model.features.3.conv.4.weight
module.base_model.features.3.conv.4.bias
module.base_model.features.3.conv.4.running_mean
module.base_model.features.3.conv.4.running_var
module.base_model.features.3.conv.4.num_batches_tracked
module.base_model.features.3.conv.6.weight
module.base_model.features.3.conv.7.weight
module.base_model.features.3.conv.7.bias
module.base_model.features.3.conv.7.running_mean
module.base_model.features.3.conv.7.running_var
module.base_model.features.3.conv.7.num_batches_tracked
module.base_model.features.3.conv.8.conv.weight
module.base_model.features.4.conv.0.weight
module.base_model.features.4.conv.1.weight
module.base_model.features.4.conv.1.bias
module.base_model.features.4.conv.1.running_mean
module.base_model.features.4.conv.1.running_var
module.base_model.features.4.conv.1.num_batches_tracked
module.base_model.features.4.conv.3.weight
module.base_model.features.4.conv.4.weight
module.base_model.features.4.conv.4.bias
module.base_model.features.4.conv.4.running_mean
module.base_model.features.4.conv.4.running_var
module.base_model.features.4.conv.4.num_batches_tracked
module.base_model.features.4.conv.6.weight
module.base_model.features.4.conv.7.weight
module.base_model.features.4.conv.7.bias
module.base_model.features.4.conv.7.running_mean
module.base_model.features.4.conv.7.running_var
module.base_model.features.4.conv.7.num_batches_tracked
module.base_model.features.4.conv.8.conv.weight
module.base_model.features.5.conv.0.weight
module.base_model.features.5.conv.1.weight
module.base_model.features.5.conv.1.bias
module.base_model.features.5.conv.1.running_mean
module.base_model.features.5.conv.1.running_var
module.base_model.features.5.conv.1.num_batches_tracked
module.base_model.features.5.conv.3.weight
module.base_model.features.5.conv.4.weight
module.base_model.features.5.conv.4.bias
module.base_model.features.5.conv.4.running_mean
module.base_model.features.5.conv.4.running_var
module.base_model.features.5.conv.4.num_batches_tracked
module.base_model.features.5.conv.6.weight
module.base_model.features.5.conv.7.weight
module.base_model.features.5.conv.7.bias
module.base_model.features.5.conv.7.running_mean
module.base_model.features.5.conv.7.running_var
module.base_model.features.5.conv.7.num_batches_tracked
module.base_model.features.5.conv.8.conv.weight
module.base_model.features.6.conv.0.weight
module.base_model.features.6.conv.1.weight
module.base_model.features.6.conv.1.bias
module.base_model.features.6.conv.1.running_mean
module.base_model.features.6.conv.1.running_var
module.base_model.features.6.conv.1.num_batches_tracked
module.base_model.features.6.conv.3.weight
module.base_model.features.6.conv.4.weight
module.base_model.features.6.conv.4.bias
module.base_model.features.6.conv.4.running_mean
module.base_model.features.6.conv.4.running_var
module.base_model.features.6.conv.4.num_batches_tracked
module.base_model.features.6.conv.6.weight
module.base_model.features.6.conv.7.weight
module.base_model.features.6.conv.7.bias
module.base_model.features.6.conv.7.running_mean
module.base_model.features.6.conv.7.running_var
module.base_model.features.6.conv.7.num_batches_tracked
module.base_model.features.6.conv.8.conv.weight
module.base_model.features.7.conv.0.weight
module.base_model.features.7.conv.1.weight
module.base_model.features.7.conv.1.bias
module.base_model.features.7.conv.1.running_mean
module.base_model.features.7.conv.1.running_var
module.base_model.features.7.conv.1.num_batches_tracked
module.base_model.features.7.conv.3.weight
module.base_model.features.7.conv.4.weight
module.base_model.features.7.conv.4.bias
module.base_model.features.7.conv.4.running_mean
module.base_model.features.7.conv.4.running_var
module.base_model.features.7.conv.4.num_batches_tracked
module.base_model.features.7.conv.6.weight
module.base_model.features.7.conv.7.weight
module.base_model.features.7.conv.7.bias
module.base_model.features.7.conv.7.running_mean
module.base_model.features.7.conv.7.running_var
module.base_model.features.7.conv.7.num_batches_tracked
module.base_model.features.7.conv.8.conv.weight
module.base_model.features.8.conv.0.weight
module.base_model.features.8.conv.1.weight
module.base_model.features.8.conv.1.bias
module.base_model.features.8.conv.1.running_mean
module.base_model.features.8.conv.1.running_var
module.base_model.features.8.conv.1.num_batches_tracked
module.base_model.features.8.conv.3.weight
module.base_model.features.8.conv.4.weight
module.base_model.features.8.conv.4.bias
module.base_model.features.8.conv.4.running_mean
module.base_model.features.8.conv.4.running_var
module.base_model.features.8.conv.4.num_batches_tracked
module.base_model.features.8.conv.6.weight
module.base_model.features.8.conv.7.weight
module.base_model.features.8.conv.7.bias
module.base_model.features.8.conv.7.running_mean
module.base_model.features.8.conv.7.running_var
module.base_model.features.8.conv.7.num_batches_tracked
module.base_model.features.8.conv.8.conv.weight
module.base_model.features.9.conv.0.weight
module.base_model.features.9.conv.1.weight
module.base_model.features.9.conv.1.bias
module.base_model.features.9.conv.1.running_mean
module.base_model.features.9.conv.1.running_var
module.base_model.features.9.conv.1.num_batches_tracked
module.base_model.features.9.conv.3.weight
module.base_model.features.9.conv.4.weight
module.base_model.features.9.conv.4.bias
module.base_model.features.9.conv.4.running_mean
module.base_model.features.9.conv.4.running_var
module.base_model.features.9.conv.4.num_batches_tracked
module.base_model.features.9.conv.6.weight
module.base_model.features.9.conv.7.weight
module.base_model.features.9.conv.7.bias
module.base_model.features.9.conv.7.running_mean
module.base_model.features.9.conv.7.running_var
module.base_model.features.9.conv.7.num_batches_tracked
module.base_model.features.9.conv.8.conv.weight
module.base_model.features.10.conv.0.weight
module.base_model.features.10.conv.1.weight
module.base_model.features.10.conv.1.bias
module.base_model.features.10.conv.1.running_mean
module.base_model.features.10.conv.1.running_var
module.base_model.features.10.conv.1.num_batches_tracked
module.base_model.features.10.conv.3.weight
module.base_model.features.10.conv.4.weight
module.base_model.features.10.conv.4.bias
module.base_model.features.10.conv.4.running_mean
module.base_model.features.10.conv.4.running_var
module.base_model.features.10.conv.4.num_batches_tracked
module.base_model.features.10.conv.6.weight
module.base_model.features.10.conv.7.weight
module.base_model.features.10.conv.7.bias
module.base_model.features.10.conv.7.running_mean
module.base_model.features.10.conv.7.running_var
module.base_model.features.10.conv.7.num_batches_tracked
module.base_model.features.10.conv.8.conv.weight
module.base_model.features.11.conv.0.weight
module.base_model.features.11.conv.1.weight
module.base_model.features.11.conv.1.bias
module.base_model.features.11.conv.1.running_mean
module.base_model.features.11.conv.1.running_var
module.base_model.features.11.conv.1.num_batches_tracked
module.base_model.features.11.conv.3.weight
module.base_model.features.11.conv.4.weight
module.base_model.features.11.conv.4.bias
module.base_model.features.11.conv.4.running_mean
module.base_model.features.11.conv.4.running_var
module.base_model.features.11.conv.4.num_batches_tracked
module.base_model.features.11.conv.6.weight
module.base_model.features.11.conv.7.weight
module.base_model.features.11.conv.7.bias
module.base_model.features.11.conv.7.running_mean
module.base_model.features.11.conv.7.running_var
module.base_model.features.11.conv.7.num_batches_tracked
module.base_model.features.11.conv.8.conv.weight
module.base_model.features.12.conv.0.weight
module.base_model.features.12.conv.1.weight
module.base_model.features.12.conv.1.bias
module.base_model.features.12.conv.1.running_mean
module.base_model.features.12.conv.1.running_var
module.base_model.features.12.conv.1.num_batches_tracked
module.base_model.features.12.conv.3.weight
module.base_model.features.12.conv.4.weight
module.base_model.features.12.conv.4.bias
module.base_model.features.12.conv.4.running_mean
module.base_model.features.12.conv.4.running_var
module.base_model.features.12.conv.4.num_batches_tracked
module.base_model.features.12.conv.6.weight
module.base_model.features.12.conv.7.weight
module.base_model.features.12.conv.7.bias
module.base_model.features.12.conv.7.running_mean
module.base_model.features.12.conv.7.running_var
module.base_model.features.12.conv.7.num_batches_tracked
module.base_model.features.12.conv.8.conv.weight
module.base_model.features.13.conv.0.weight
module.base_model.features.13.conv.1.weight
module.base_model.features.13.conv.1.bias
module.base_model.features.13.conv.1.running_mean
module.base_model.features.13.conv.1.running_var
module.base_model.features.13.conv.1.num_batches_tracked
module.base_model.features.13.conv.3.weight
module.base_model.features.13.conv.4.weight
module.base_model.features.13.conv.4.bias
module.base_model.features.13.conv.4.running_mean
module.base_model.features.13.conv.4.running_var
module.base_model.features.13.conv.4.num_batches_tracked
module.base_model.features.13.conv.6.weight
module.base_model.features.13.conv.7.weight
module.base_model.features.13.conv.7.bias
module.base_model.features.13.conv.7.running_mean
module.base_model.features.13.conv.7.running_var
module.base_model.features.13.conv.7.num_batches_tracked
module.base_model.features.13.conv.8.conv.weight
module.base_model.features.14.conv.0.weight
module.base_model.features.14.conv.1.weight
module.base_model.features.14.conv.1.bias
module.base_model.features.14.conv.1.running_mean
module.base_model.features.14.conv.1.running_var
module.base_model.features.14.conv.1.num_batches_tracked
module.base_model.features.14.conv.3.weight
module.base_model.features.14.conv.4.weight
module.base_model.features.14.conv.4.bias
module.base_model.features.14.conv.4.running_mean
module.base_model.features.14.conv.4.running_var
module.base_model.features.14.conv.4.num_batches_tracked
module.base_model.features.14.conv.6.weight
module.base_model.features.14.conv.7.weight
module.base_model.features.14.conv.7.bias
module.base_model.features.14.conv.7.running_mean
module.base_model.features.14.conv.7.running_var
module.base_model.features.14.conv.7.num_batches_tracked
module.base_model.features.14.conv.8.conv.weight
module.base_model.features.15.conv.0.weight
module.base_model.features.15.conv.1.weight
module.base_model.features.15.conv.1.bias
module.base_model.features.15.conv.1.running_mean
module.base_model.features.15.conv.1.running_var
module.base_model.features.15.conv.1.num_batches_tracked
module.base_model.features.15.conv.3.weight
module.base_model.features.15.conv.4.weight
module.base_model.features.15.conv.4.bias
module.base_model.features.15.conv.4.running_mean
module.base_model.features.15.conv.4.running_var
module.base_model.features.15.conv.4.num_batches_tracked
module.base_model.features.15.conv.6.weight
module.base_model.features.15.conv.7.weight
module.base_model.features.15.conv.7.bias
module.base_model.features.15.conv.7.running_mean
module.base_model.features.15.conv.7.running_var
module.base_model.features.15.conv.7.num_batches_tracked
module.base_model.features.15.conv.8.conv.weight
module.base_model.features.16.conv.0.weight
module.base_model.features.16.conv.1.weight
module.base_model.features.16.conv.1.bias
module.base_model.features.16.conv.1.running_mean
module.base_model.features.16.conv.1.running_var
module.base_model.features.16.conv.1.num_batches_tracked
module.base_model.features.16.conv.3.weight
module.base_model.features.16.conv.4.weight
module.base_model.features.16.conv.4.bias
module.base_model.features.16.conv.4.running_mean
module.base_model.features.16.conv.4.running_var
module.base_model.features.16.conv.4.num_batches_tracked
module.base_model.features.16.conv.6.weight
module.base_model.features.16.conv.7.weight
module.base_model.features.16.conv.7.bias
module.base_model.features.16.conv.7.running_mean
module.base_model.features.16.conv.7.running_var
module.base_model.features.16.conv.7.num_batches_tracked
module.base_model.features.16.conv.8.conv.weight
module.base_model.features.17.conv.0.weight
module.base_model.features.17.conv.1.weight
module.base_model.features.17.conv.1.bias
module.base_model.features.17.conv.1.running_mean
module.base_model.features.17.conv.1.running_var
module.base_model.features.17.conv.1.num_batches_tracked
module.base_model.features.17.conv.3.weight
module.base_model.features.17.conv.4.weight
module.base_model.features.17.conv.4.bias
module.base_model.features.17.conv.4.running_mean
module.base_model.features.17.conv.4.running_var
module.base_model.features.17.conv.4.num_batches_tracked
module.base_model.features.17.conv.6.weight
module.base_model.features.17.conv.7.weight
module.base_model.features.17.conv.7.bias
module.base_model.features.17.conv.7.running_mean
module.base_model.features.17.conv.7.running_var
module.base_model.features.17.conv.7.num_batches_tracked
module.base_model.features.17.conv.8.conv.weight
module.base_model.features.18.0.weight
module.base_model.features.18.1.weight
module.base_model.features.18.1.bias
module.base_model.features.18.1.running_mean
module.base_model.features.18.1.running_var
module.base_model.features.18.1.num_batches_tracked
module.base_model.classifier.weight
module.base_model.classifier.bias